server:
  port: 10010

spring:
  datasource:
    username: root
    password: root
    url: jdbc:mysql://192.168.199.206:3306/gulimall_pms?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.jdbc.Driver
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.199.206:8848
    alicloud:
      access-key: LTAI4Fec4n99HjGECZGjxVx8
      secret-key: By1KnhZRjUR8imapMzYTqR6m0F1s1n
      oss:
        endpoint: oss-cn-beijing.aliyuncs.com
  messages:
    encoding: UTF-8
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
  thymeleaf:
    cache: false
  redis:
    host: 192.168.199.206
    port: 6379

mybatis-plus:
  mapper-location: classpath*:/mapper/**/*.xml
  global-config:
    db-config:
      id-type: auto
      logic-delete-value: 1
      logic-not-delete-value: 0


logging:
  level:
    com.atguigu.gulimall: info
    org.springframework.cloud.openfeign: debug
    org.springframework.cloud.sleuth: debug


